### PR TITLE
Make plots selectable

### PR DESCRIPTION
**Pull request by laurafroelich**
* Add plot in middle of dashboard that shows simulated data
* Make data pattern and noise plots selectable to configure simulated data
* Fix conflict in versions that made package uninstallable by decreasing minimum required version of pandas
* Switch to Poetry for package management and dependency resolving

### CODE REVIEW

**Comment by rhaDHI** [comment]
I cannot pip install the package. Something wrong with dependency resolving for pandas and numpy with the restrictions in the setup. I've tried a bunch of things with different errors. Maybe setup a test pipeline (see anomalydetection repo for github action example) to make sure it is not just me?

**Comment by laurafroelich** [comment]
> 
> 
> I cannot pip install the package. Something wrong with dependency resolving for pandas and numpy with the restrictions in the setup. I've tried a bunch of things with different errors. Maybe setup a test pipeline (see anomalydetection repo for github action example) to make sure it is not just me?

Good idea to get a pipeline set up that at least checks installation.
And no, it is not just you. While I even tried to specify the exact versions I have on my system, pip was still not able to resolve dependencies in the pipeline. In the end, I decided to try with Poetry, which works. So I suggest we switch to Poetry for this repo.

**Comment by ecomodeller** [comment]
I wonder what dependency that is causing such trouble??

I use Dash for a lot of examples in our Data Assimilation course https://randomdash.azurewebsites.net/  and have not run into similar problems, but I did not create a package for it.

**Comment by laurafroelich** [comment]
I agree, it's quite odd. Yes, I was a bit unsure whether to make a package out of it or not. I thought it would be easier in terms of installation, but maybe not... we could maintain a requirements.txt file as well

**Comment by laurafroelich** [comment]
@rhaDHI @ecomodeller do you think we should make other changes to this PR before merging?

**Comment by rhaDHI** [comment]
@laurafroelich Nope. It works now :-) Tested both poetry and requirements.

**Review by rhaDHI — APPROVED** [review]

**Comment by laurafroelich** [comment]
> 
> 
> @laurafroelich Nope. It works now :-) Tested both poetry and requirements.

@rhaDHI Thanks!

**Pull request merged**
